// This file was automatically created for you.
// Do not edit this file unless you really know what you are doing.

const config = require('./package')

const matcher = /^@awtrix\/(.+)-app$/
const apps = Object.keys(config.dependencies)
  .filter(dep => dep.match(matcher))
  .reduce((result, dep) => {
    result[dep] = require(dep)
    return result
  }, {})

module.exports = {
  apps, config: config.awtrix,
}
